### Authorization password grant as user
POST http://localhost:8180/realms/client_application/protocol/openid-connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

client_id=bmac_application&client_secret=ZAjXEbqWWLMZceGEkCOJFf5LOjMYN8jc&username=sam&password=password&grant_type=password&scope=openid

> {%
    client.global.set("access_token", response.body.access_token);
%}


### Authorization password grant as admin
POST http://localhost:8180/realms/client_application/protocol/openid-connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

client_id=bmac_application&client_secret=ZAjXEbqWWLMZceGEkCOJFf5LOjMYN8jc&username=admin&password=password&grant_type=password&scope=openid

> {%
    client.global.set("access_token", response.body.access_token);
%}



### Get all new products
GET http://localhost:8082/api/product/getNewProducts
Authorization: Bearer {{access_token}}

### Get all products
GET http://localhost:8082/api/product/all
Authorization: Bearer {{access_token}}

### set price
POST http://localhost:8082/api/product/setPrice/6.0/6f8d5a2b-aa4e-4b71-a33d-182ccda1d3d0
Authorization: Bearer {{access_token}}